apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-manager-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - update
      - delete
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - update
      - delete
      - list
      - watch